import { mkdirSync } from "node:fs"
import { build } from "esbuild"

mkdirSync("api", { recursive: true })

await build({
  entryPoints: ["server/vercel-handler.ts"],
  bundle: true,
  platform: "node",
  format: "esm",
  outfile: "api/list.js",
  packages: "external",
  banner: {
    js: "/* generated by scripts/build-api.mjs — do not edit */",
  },
  logLevel: "info",
})
