/* generated by scripts/build-api.mjs — do not edit */

// server/vercel-handler.ts
import { handle } from "hono/vercel";

// server/app.ts
import { Hono } from "hono";
import { HTTPException } from "hono/http-exception";

// server/auth.ts
import { createClient } from "@supabase/supabase-js";
function getSupabaseUrl() {
  return process.env.SUPABASE_URL ?? process.env.VITE_SUPABASE_URL;
}
function getSupabaseKey() {
  return process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.VITE_SUPABASE_PUBLISHABLE_KEY;
}
function isAuthConfigured() {
  return Boolean(getSupabaseUrl() && getSupabaseKey());
}
function displayName(user) {
  const metadataName = user.user_metadata?.name;
  if (typeof metadataName === "string" && metadataName.trim()) {
    return metadataName.trim();
  }
  return user.email?.split("@")[0] || "Conta";
}
async function requireUser(request) {
  const url = getSupabaseUrl();
  const key = getSupabaseKey();
  if (!url || !key) {
    return null;
  }
  const header = request.headers.get("authorization");
  const token = header?.startsWith("Bearer ") ? header.slice(7).trim() : "";
  if (!token) {
    return null;
  }
  const supabase = createClient(url, key);
  const { data, error } = await supabase.auth.getUser(token);
  if (error || !data.user?.id || !data.user.email) {
    return null;
  }
  return {
    id: data.user.id,
    email: data.user.email.trim().toLowerCase(),
    name: displayName(data.user)
  };
}

// server/db.ts
import { neon } from "@neondatabase/serverless";
function isDatabaseConfigured() {
  return Boolean(process.env.DATABASE_URL);
}
function getSql() {
  const url = process.env.DATABASE_URL;
  if (!url) {
    throw new Error("DATABASE_URL ausente.");
  }
  return neon(url);
}

// server/list.ts
var MAX_ITEM_NAME_LENGTH = 80;
var MAX_PRICE_CENTS = 99999999;
var MAX_QUANTITY = 9999;
var MAX_ITEMS = 200;
var uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function normalizeItemId(id) {
  return uuidPattern.test(id) ? id : crypto.randomUUID();
}
function toShoppingItem(value) {
  if (typeof value !== "object" || value === null) {
    return null;
  }
  const item = value;
  if (typeof item.id !== "string" || item.id.trim() === "" || typeof item.name !== "string" || item.name.trim() === "" || item.name.trim().length > MAX_ITEM_NAME_LENGTH || typeof item.quantity !== "number" || !Number.isInteger(item.quantity) || item.quantity < 1 || item.quantity > MAX_QUANTITY || typeof item.priceCents !== "number" || !Number.isInteger(item.priceCents) || item.priceCents <= 0 || item.priceCents > MAX_PRICE_CENTS) {
    return null;
  }
  return {
    id: item.id,
    name: item.name.trim(),
    priceCents: item.priceCents,
    quantity: item.quantity
  };
}
function toInsertRows(items) {
  return items.map((item, position) => ({
    id: item.id,
    name: item.name,
    price_cents: item.priceCents,
    quantity: item.quantity,
    position
  }));
}
function toShoppingItems(rows) {
  return rows.map((row) => ({
    id: row.id,
    name: row.name,
    priceCents: row.price_cents,
    quantity: row.quantity
  }));
}
function parseListBody(body) {
  const record = typeof body === "object" && body !== null ? body : null;
  if (!Array.isArray(record?.items)) {
    return { ok: false, error: "Lista inv\xE1lida." };
  }
  const items = [];
  const seen = /* @__PURE__ */ new Set();
  let skipped = false;
  for (const value of record.items) {
    const item = toShoppingItem(value);
    if (item === null || seen.has(item.id)) {
      skipped = true;
      continue;
    }
    if (items.length >= MAX_ITEMS) {
      skipped = true;
      continue;
    }
    const normalized = {
      ...item,
      id: normalizeItemId(item.id)
    };
    seen.add(item.id);
    seen.add(normalized.id);
    items.push(normalized);
  }
  if (record.items.length > 0 && items.length === 0) {
    return { ok: false, error: "Lista inv\xE1lida." };
  }
  return {
    ok: true,
    items,
    warning: skipped ? "Alguns itens salvos foram ignorados porque estavam inv\xE1lidos." : null
  };
}
async function ensureOpenPurchase(user) {
  const sql = getSql();
  await sql`
    insert into profiles (id, name, email)
    values (${user.id}::uuid, ${user.name}, ${user.email})
    on conflict (id) do update
    set
      name = excluded.name,
      email = excluded.email,
      updated_at = now()
  `;
  await sql`
    insert into purchases (id, user_id, status)
    select gen_random_uuid(), ${user.id}::uuid, 'open'
    where not exists (
      select 1
      from purchases
      where user_id = ${user.id}::uuid
        and status = 'open'
    )
  `;
}
async function listOpenItems(user) {
  await ensureOpenPurchase(user);
  const sql = getSql();
  const rows = await sql`
    select i.id, i.name, i.price_cents, i.quantity
    from purchase_items i
    join purchases p on p.id = i.purchase_id
    where p.user_id = ${user.id}::uuid
      and p.status = 'open'
    order by i.position
  `;
  return toShoppingItems(rows);
}
async function replaceOpenItems(user, items) {
  await ensureOpenPurchase(user);
  const sql = getSql();
  const payload = JSON.stringify(toInsertRows(items));
  await sql`
    with purchase as (
      select id
      from purchases
      where user_id = ${user.id}::uuid
        and status = 'open'
    ),
    deleted as (
      delete from purchase_items
      where purchase_id in (select id from purchase)
    )
    insert into purchase_items (
      id,
      purchase_id,
      name,
      price_cents,
      quantity,
      position
    )
    select
      x.id,
      (select id from purchase),
      x.name,
      x.price_cents,
      x.quantity,
      x.position
    from jsonb_to_recordset(${payload}::jsonb) as x(
      id uuid,
      name text,
      price_cents integer,
      quantity integer,
      position integer
    )
  `;
  await sql`
    update purchases
    set updated_at = now()
    where user_id = ${user.id}::uuid
      and status = 'open'
  `;
}

// server/app.ts
var app = new Hono();
app.onError((error, context) => {
  if (error instanceof HTTPException) {
    return error.getResponse();
  }
  console.error(error);
  return context.json(
    { error: "N\xE3o foi poss\xEDvel sincronizar a lista." },
    500
  );
});
app.get("/api/list", async (context) => {
  if (!isAuthConfigured()) {
    return context.json({ error: "Autentica\xE7\xE3o do servidor n\xE3o configurada." }, 503);
  }
  const user = await requireUser(context.req.raw);
  if (!user) {
    return context.json({ error: "N\xE3o autenticado." }, 401);
  }
  if (!isDatabaseConfigured()) {
    return context.json({ error: "Banco n\xE3o configurado." }, 503);
  }
  const items = await listOpenItems(user);
  return context.json({ items });
});
app.put("/api/list", async (context) => {
  if (!isAuthConfigured()) {
    return context.json({ error: "Autentica\xE7\xE3o do servidor n\xE3o configurada." }, 503);
  }
  const user = await requireUser(context.req.raw);
  if (!user) {
    return context.json({ error: "N\xE3o autenticado." }, 401);
  }
  if (!isDatabaseConfigured()) {
    return context.json({ error: "Banco n\xE3o configurado." }, 503);
  }
  const parsed = parseListBody(await context.req.json());
  if (!parsed.ok) {
    return context.json({ error: parsed.error }, 400);
  }
  await replaceOpenItems(user, parsed.items);
  return context.json({
    items: parsed.items,
    warning: parsed.warning
  });
});

// server/vercel-handler.ts
var config = {
  runtime: "nodejs"
};
var vercel_handler_default = handle(app);
export {
  config,
  vercel_handler_default as default
};
